import os
import sys
import json

template = {
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe build active file",
            "command": "C:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": True
            },
            "detail": "Task generated by Debugger and a Python Script."
        }
    ],
    "version": "2.0.0"
}

ignore = ["tests.cpp", "main.cpp"]

def main(fname:str=None):
    if fname is not None:
          ignore.append(fname)
    cpp_files = []
    for f in os.listdir('./'):
        if not f in ignore and f[-4:] == ".cpp":
            cpp_files.append(f)
    template["tasks"][0]["args"] += ["-fdiagnostics-color=always", "-g", "${file}"]
    template["tasks"][0]["args"] += cpp_files
    template["tasks"][0]["args"] += ["-o", "${fileDirname}\\${fileBasenameNoExtension}.exe"]

    with open('./.vscode/tasks.json', 'w') as json_file:
        json.dump(template, json_file)

    print("Generated Tasks")

if __name__ == "__main__":
    fname = None
    if len(sys.argv) > 1:
        fname = sys.argv[1]
    main(fname)